
  create table "public"."assignments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "port_event" uuid not null,
    "assignee" uuid not null,
    "standby_minutes" integer not null,
    "duration_minutes" integer not null
      );


alter table "public"."assignments" enable row level security;

alter table "public"."port_events" add column "default_duration_minutes" integer not null default 120;

alter table "public"."port_events" add column "default_standby_minutes" integer not null default 30;

alter table "public"."port_events" add column "is_public" boolean not null default false;

alter table "public"."port_events" add column "max_assignees" integer not null;

CREATE UNIQUE INDEX assignments_pkey ON public.assignments USING btree (id);

CREATE UNIQUE INDEX assignments_port_event_assignee_key ON public.assignments USING btree (port_event, assignee);

alter table "public"."assignments" add constraint "assignments_pkey" PRIMARY KEY using index "assignments_pkey";

alter table "public"."assignments" add constraint "assignments_assignee_fkey" FOREIGN KEY (assignee) REFERENCES public.profiles(id) not valid;

alter table "public"."assignments" validate constraint "assignments_assignee_fkey";

alter table "public"."assignments" add constraint "assignments_port_event_assignee_key" UNIQUE using index "assignments_port_event_assignee_key";

alter table "public"."assignments" add constraint "assignments_port_event_fkey" FOREIGN KEY (port_event) REFERENCES public.port_events(id) not valid;

alter table "public"."assignments" validate constraint "assignments_port_event_fkey";

grant delete on table "public"."assignments" to "anon";

grant insert on table "public"."assignments" to "anon";

grant references on table "public"."assignments" to "anon";

grant select on table "public"."assignments" to "anon";

grant trigger on table "public"."assignments" to "anon";

grant truncate on table "public"."assignments" to "anon";

grant update on table "public"."assignments" to "anon";

grant delete on table "public"."assignments" to "authenticated";

grant insert on table "public"."assignments" to "authenticated";

grant references on table "public"."assignments" to "authenticated";

grant select on table "public"."assignments" to "authenticated";

grant trigger on table "public"."assignments" to "authenticated";

grant truncate on table "public"."assignments" to "authenticated";

grant update on table "public"."assignments" to "authenticated";

grant delete on table "public"."assignments" to "service_role";

grant insert on table "public"."assignments" to "service_role";

grant references on table "public"."assignments" to "service_role";

grant select on table "public"."assignments" to "service_role";

grant trigger on table "public"."assignments" to "service_role";

grant truncate on table "public"."assignments" to "service_role";

grant update on table "public"."assignments" to "service_role";


